USE [NGANHANG]
GO

GRANT EXECUTE ON OBJECT::[dbo].[SP_TimThongTinKhachHangTheoSTK_TatCaChiNhanh] TO NGANHANG
GRANT EXECUTE ON OBJECT::[dbo].[SP_LietKeTaiKhoanMoiMo_TheoChiNhanh] TO NGANHANG
GRANT EXECUTE ON OBJECT::[dbo].[SP_XemSKKHACHHANG] TO NGANHANG
GRANT EXECUTE ON OBJECT::[dbo].[SP_TimThongTinKhachHangTheoSTK] TO NGANHANG
GO
